//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebshopClient.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WebshopService")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QntyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Qnty {
            get {
                return this.QntyField;
            }
            set {
                if ((this.QntyField.Equals(value) != true)) {
                    this.QntyField = value;
                    this.RaisePropertyChanged("Qnty");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/WebshopService")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CreditField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Credit {
            get {
                return this.CreditField;
            }
            set {
                if ((this.CreditField.Equals(value) != true)) {
                    this.CreditField = value;
                    this.RaisePropertyChanged("Credit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IWebshopService")]
    public interface IWebshopService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/GetProducts", ReplyAction="http://tempuri.org/IWebshopService/GetProductsResponse")]
        WebshopClient.ServiceReference.Product[] GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/GetProducts", ReplyAction="http://tempuri.org/IWebshopService/GetProductsResponse")]
        System.Threading.Tasks.Task<WebshopClient.ServiceReference.Product[]> GetProductsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/InsertCustomer", ReplyAction="http://tempuri.org/IWebshopService/InsertCustomerResponse")]
        bool InsertCustomer(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/InsertCustomer", ReplyAction="http://tempuri.org/IWebshopService/InsertCustomerResponse")]
        System.Threading.Tasks.Task<bool> InsertCustomerAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/GetCustomer", ReplyAction="http://tempuri.org/IWebshopService/GetCustomerResponse")]
        WebshopClient.ServiceReference.Customer GetCustomer(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/GetCustomer", ReplyAction="http://tempuri.org/IWebshopService/GetCustomerResponse")]
        System.Threading.Tasks.Task<WebshopClient.ServiceReference.Customer> GetCustomerAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/Buy", ReplyAction="http://tempuri.org/IWebshopService/BuyResponse")]
        string Buy(WebshopClient.ServiceReference.Product product, WebshopClient.ServiceReference.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/Buy", ReplyAction="http://tempuri.org/IWebshopService/BuyResponse")]
        System.Threading.Tasks.Task<string> BuyAsync(WebshopClient.ServiceReference.Product product, WebshopClient.ServiceReference.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/GetQnty", ReplyAction="http://tempuri.org/IWebshopService/GetQntyResponse")]
        int GetQnty(WebshopClient.ServiceReference.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/GetQnty", ReplyAction="http://tempuri.org/IWebshopService/GetQntyResponse")]
        System.Threading.Tasks.Task<int> GetQntyAsync(WebshopClient.ServiceReference.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/GetCart", ReplyAction="http://tempuri.org/IWebshopService/GetCartResponse")]
        WebshopClient.ServiceReference.Product[] GetCart(WebshopClient.ServiceReference.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/GetCart", ReplyAction="http://tempuri.org/IWebshopService/GetCartResponse")]
        System.Threading.Tasks.Task<WebshopClient.ServiceReference.Product[]> GetCartAsync(WebshopClient.ServiceReference.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/GetCredit", ReplyAction="http://tempuri.org/IWebshopService/GetCreditResponse")]
        decimal GetCredit(WebshopClient.ServiceReference.Customer customer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWebshopService/GetCredit", ReplyAction="http://tempuri.org/IWebshopService/GetCreditResponse")]
        System.Threading.Tasks.Task<decimal> GetCreditAsync(WebshopClient.ServiceReference.Customer customer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWebshopServiceChannel : WebshopClient.ServiceReference.IWebshopService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebshopServiceClient : System.ServiceModel.ClientBase<WebshopClient.ServiceReference.IWebshopService>, WebshopClient.ServiceReference.IWebshopService {
        
        public WebshopServiceClient() {
        }
        
        public WebshopServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebshopServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebshopServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebshopServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebshopClient.ServiceReference.Product[] GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public System.Threading.Tasks.Task<WebshopClient.ServiceReference.Product[]> GetProductsAsync() {
            return base.Channel.GetProductsAsync();
        }
        
        public bool InsertCustomer(string username, string password) {
            return base.Channel.InsertCustomer(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> InsertCustomerAsync(string username, string password) {
            return base.Channel.InsertCustomerAsync(username, password);
        }
        
        public WebshopClient.ServiceReference.Customer GetCustomer(string username, string password) {
            return base.Channel.GetCustomer(username, password);
        }
        
        public System.Threading.Tasks.Task<WebshopClient.ServiceReference.Customer> GetCustomerAsync(string username, string password) {
            return base.Channel.GetCustomerAsync(username, password);
        }
        
        public string Buy(WebshopClient.ServiceReference.Product product, WebshopClient.ServiceReference.Customer customer) {
            return base.Channel.Buy(product, customer);
        }
        
        public System.Threading.Tasks.Task<string> BuyAsync(WebshopClient.ServiceReference.Product product, WebshopClient.ServiceReference.Customer customer) {
            return base.Channel.BuyAsync(product, customer);
        }
        
        public int GetQnty(WebshopClient.ServiceReference.Product product) {
            return base.Channel.GetQnty(product);
        }
        
        public System.Threading.Tasks.Task<int> GetQntyAsync(WebshopClient.ServiceReference.Product product) {
            return base.Channel.GetQntyAsync(product);
        }
        
        public WebshopClient.ServiceReference.Product[] GetCart(WebshopClient.ServiceReference.Customer customer) {
            return base.Channel.GetCart(customer);
        }
        
        public System.Threading.Tasks.Task<WebshopClient.ServiceReference.Product[]> GetCartAsync(WebshopClient.ServiceReference.Customer customer) {
            return base.Channel.GetCartAsync(customer);
        }
        
        public decimal GetCredit(WebshopClient.ServiceReference.Customer customer) {
            return base.Channel.GetCredit(customer);
        }
        
        public System.Threading.Tasks.Task<decimal> GetCreditAsync(WebshopClient.ServiceReference.Customer customer) {
            return base.Channel.GetCreditAsync(customer);
        }
    }
}
