
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebshopService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://localhost:8733/Design_Time_Addresses/WinkelService/Service1/?singleWsdl")
public class WebshopService
    extends Service
{

    private final static URL WEBSHOPSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSHOPSERVICE_EXCEPTION;
    private final static QName WEBSHOPSERVICE_QNAME = new QName("http://tempuri.org/", "WebshopService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8733/Design_Time_Addresses/WinkelService/Service1/?singleWsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSHOPSERVICE_WSDL_LOCATION = url;
        WEBSHOPSERVICE_EXCEPTION = e;
    }

    public WebshopService() {
        super(__getWsdlLocation(), WEBSHOPSERVICE_QNAME);
    }

    public WebshopService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSHOPSERVICE_QNAME, features);
    }

    public WebshopService(URL wsdlLocation) {
        super(wsdlLocation, WEBSHOPSERVICE_QNAME);
    }

    public WebshopService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSHOPSERVICE_QNAME, features);
    }

    public WebshopService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebshopService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWebshopService
     */
    @WebEndpoint(name = "BasicHttpBinding_IWebshopService")
    public IWebshopService getBasicHttpBindingIWebshopService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWebshopService"), IWebshopService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWebshopService
     */
    @WebEndpoint(name = "BasicHttpBinding_IWebshopService")
    public IWebshopService getBasicHttpBindingIWebshopService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IWebshopService"), IWebshopService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSHOPSERVICE_EXCEPTION!= null) {
            throw WEBSHOPSERVICE_EXCEPTION;
        }
        return WEBSHOPSERVICE_WSDL_LOCATION;
    }

}
